### ISSUE TITLE
TO_DO VARIABLE

### ISSUE THREAD

**Issue by noraworld** [noraworld/github-actions-sandbox#63]
# to-do
* [ ] A
* [ ] B
* [ ] C
* [ ] D
* [ ] E
* [ ] F
* [ ] [ガムテープ](https://github.com/noraworld/to-do/issues/162)
* [ ] [Disposable cups](https://github.com/noraworld/to-do/issues/161)
* [ ] [Wet wipes](https://github.com/noraworld/to-do/issues/160)

* [ ] [ImmiAccount アカウントを作る](https://github.com/noraworld/to-do/issues/164)
* [ ] [ごほうびシステムを導入する](https://github.com/noraworld/to-do/issues/163)
